version: "2.2"
services:
  db:
    image: "mariadb"
    container_name: "database_container"
    environment:
      MYSQL_ROOT_PASSWORD: "123456" # 可以在这里设置数据库信息，也可以在node的项目中去设置数据库信息
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "123456"
      MYSQL_DATABASE: "test"
    volumes:
      - "db_data:/var/lib/mysql"
    ports:
      - "3306:3306"
  web:
    image: "nginx"
    container_name: "nginx_container"
    ports:
      - "8080:80"
    volumes:
      - "./images/nginx/conf.d:/etc/nginx/conf.d" #把容器内nginx的配置文件映射到外部
      - "./images/node/app/public:/public"
    depends_on:
      - node # 服务依赖于后端的node服务
  node:
    container_name: "node_container"
    build:
      context: "./images/node"
      dockerfile: "Dockerfile"
    ports:
      - "3000:3000"
    depends_on:
      - db # 服务依赖于数据库服务
volumes:
  db_data:
    driver: local
